[package]
name = "nobot"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "7.0"
linera-sdk = "0.15.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
log = "0.4"

[lib]
crate-type = ["cdylib"]
